global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'service-health'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://vp-auth-service:8000/health
        - http://vp-video-service:8000/health
        - http://host.docker.internal:32514/health
        - http://host.docker.internal:32515/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: vp-blackbox-exporter:9115

  - job_name: 'observability'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'vp-prometheus:9090'
        - 'vp-loki:3100'
        - 'vp-blackbox-exporter:9115'

  - job_name: 'traefik'
    static_configs:
      - targets: ['vp-traefik:8080'] # Porta do dashboard/api do traefik

  - job_name: 'video-services'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - 'vp-auth-service:8000'
        - 'vp-video-service:8000'
        - 'host.docker.internal:32514'
        - 'host.docker.internal:32515'